### ISSUE TITLE
[FEAT] Add audio, file and video blocks to Blocks component

### ISSUE THREAD

**Issue by SalahAdDin** [christophebe/strapi-julius-editor#1]
Since the Blocks component is a WYSIWYG editor and often the authors want to add videos, audio, files, or embeds, it would be good that this editor also supports those blocks.

We could find an example on the following  EditorJS plugins:
https://github.com/editor-js/attaches
https://github.com/weekwood/editorjs-video
https://github.com/renanrider/editorjs-audio-player
https://github.com/editor-js/embed

This plugin can be a plugin for video: https://github.com/sereneinserenade/tiptap-extension-video, https://github.com/KID-1912/tiptap-extension-video

Hashtags: https://github.com/ogzhnaydn38/tiptap-extension-hashtag

This one is for search and replace: https://github.com/sereneinserenade/tiptap-search-and-replace

And this feature for text direction: https://github.com/amirhhashemi/tiptap-text-direction

Forget all of them, there are a very good resource for getting such extensions plus a better design:
https://github.com/edificeio/edifice-ui/tree/develop/packages/tiptap/extensions
https://github.com/edificeio/edifice-ui/tree/develop/packages/react/editor

Here is an example:
https://edificeio.github.io/edifice-ui/?path=/docs/tiptap-editortoolbar--docs

It includes a replacement for the emoji extension and others, giving a huge potential to this plugin!

What do you think?

**Comment by christophebe** [comment]
I'm not sure if I understood your question correctly, but it is already possible to add those types of contents: video, image in the editor. 

For audio, you'd have to check whether there isn't an extension in Tiptap. 
For files, you can add them in the Strapi Media lib and make a link in a content. 

![image](https://github.com/christophebe/strapi-julius-editor/assets/5743745/f751efc2-60a3-4f7f-b436-c6d2666befa4)


Check also the list of the Tiptap extensions : https://tiptap.dev/docs/editor/extensions
If necessary, we would need to know how to add more extensions to the editor configuration in Strapi. 

<img width="1666" alt="image" src="https://github.com/christophebe/strapi-julius-editor/assets/5743745/a1576afd-bce8-4157-bfe7-f5ff34bebdb7">

**Comment by christophebe** [comment]
Please, if an extension is missing, make a pull request.

Thanks
