### ISSUE TITLE
YouTube embed issue

### ISSUE THREAD

**Issue by devmoatassem** [christophebe/strapi-julius-editor#4]
Hey I can't embed youtube videos. 
Getting an error like this: 
_This content is blocked. Contact the site owner to fix the issue._

![image](https://github.com/christophebe/strapi-julius-editor/assets/62389924/284f709f-1bcd-4cd5-8cc4-6575fef7dbb0)

To me the issue seems to be related to some strapi security modifications required, if that's the case then documentation of plugin needs an update

**Getting the same error on Strapi 4.20 and 4.25.1**

**Comment by devmoatassem** [comment]
@christophebe  I have resolved the issue, to help others avoid it I would like to make some adittion to docs, will create a PR you may merge it, Please respond if you think I should add a PR ?

**Comment by christophebe** [comment]
Hi, 

Yes a PR is perfect. 

Thanks a lot !

**Comment by christophebe** [comment]
Hi, If you have no time to make a PR, please tell me your suggestion to improve the doc. 

Thanks

**Comment by devmoatassem** [comment]
Sorry I didn't receive the notification of the first reply. I'll create a PR tomorrow.

**Comment by devmoatassem** [comment]
Created PR [https://github.com/christophebe/strapi-julius-editor/pull/5](https://github.com/christophebe/strapi-julius-editor/pull/5) with updates.

**Comment by christophebe** [comment]
Thanks !
